# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

workspace 'LeanCloudSocialDemo.xcworkspace'

target 'LeanCloudSocial' do
    xcodeproj '../LeanCloudSocial.xcodeproj'
    pod 'AVOSCloud', '~> 3.1'
    pod 'AFNetworking', '~> 2.0'
end

target 'LeanCloudSocialTests' do
    xcodeproj '../LeanCloudSocial.xcodeproj'
end


target 'LeanCloudSocialDemo' do
    xcodeproj 'LeanCloudSocialDemo.xcodeproj'
    pod 'LeanCloudSocial', :path => '../'
end

target 'LeanCloudSocialDemoTests' do
    xcodeproj 'LeanCloudSocialDemo.xcodeproj'
end

