# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LeanCloudSocialDemo' do
    pod 'LeanCloudSocial', :path => '../'
end

target 'LeanCloudSocialDemoTests' do

end

